#import "macros.typ": *
#import "diagrams.typ": *


#let coxeter_systems = [
  *Dihedral groups*#h(-0.25em), well known from elementary group theory, encode the symmetries of regular polygons.
  For example, the square admits eight fundamental symmetries: reflections through its horizontal and vertical axes and two diagonals, and rotations through 90, 180, and 270 degrees.

  #dihedral_group_diagram

  Through the transformation $t := s r$, we can describe this group solely in terms of reflections, which gives rise to the notion of a *geometric reflection group*#h(-0.3em)---#h(0em)a more generic group generated by reflections across a particular set of hyperplanes $H_i$ acting on Euclidean, hyperbolic, or spherical spaces.

  Abstracting this further, beyond purely geometric considerations, produces the *Coxeter group*#h(-0.25em), defined by the presentation
  $
    W = gen(s_1\, s_2\, dots\, s_n | (s_i s_j)^(m_(i j)) = 1)
  $
  where $m_(i i) = 1$ and $m_(i j) = m_(j i) in {2, 3, dots} union {infty}$ for all distinct $i, j$.
  Observe this definition implies each generator $s_i$ is an involution and thus corresponds to a reflection.
  Denoting the indexing set ${s_i}$ by $S$, we define a *Coxeter System* as the pair $(W, S)$.

  Importantly, for some $T subset.eq S$, we define the *parabolic subgroup* $W_T$ of $W$ by $W_T = gen(T)$; we can show that $(W_T, T)$ is a Coxeter System as well.
]

#let chambers_and_nerves = [
  #pad(bottom: 0.2cm)[
    For the following definitions let $(W, S)$ be a Coxeter system. Then, for the diagrams shown below, let $S^((0)) = {s_0, s_1, s_2, s_3}$, $S^((1)) = {s, t, u}$, and $
      W^((0))
        &= angle.l s_0, s_1, s_2, s_3 bar.v s_i^2 = (s_i s_(i + 1))^2 = 1, forall i in ZZ_4 angle.r \
      W^((1))
        &= angle.l s, t, u bar.v s^2 = t^2 = u^2 = 1; (s t)^3 = 1 angle.r iso D_6 * C_2.
    $
  ]
  #grid(
    columns: 2,
    [
      - An *abstract simplicial complex* is a set $V$, called the vertex set, and a collection $X$ of finite subsets of $V$ such that:
        - ${v} in X$ for all $v in V$
        - if $Delta in X$ with $Delta' subset.eq Delta$ then $Delta' in X$

      - The *nerve* of $(W, S)$, denoted by $L = L(W, S)$, is the abstract simplicial complex with a simplex $sigma_T$ for each $T subset.eq S$, where $T eq.not emptyset$ and $W_T$ is finite

      - Let $L'$ be the *barycentric subdivision* of $L$ (adding additional simplices at the barycenters of existing simplices representing the parabolic subgroups $W_T$)

      - The *chamber* $K$ is the cone on $L'$. For each $s in S$, we can define the closed star in $L'$ of the vertex $s$ to be $K_s subset.eq K$

      - The point added by the cone is the empty set $emptyset$ in the simplicial complex, which represents the subgroup $W_emptyset$
    ],
    gutter: 2em,
    dihedral_group_diagram,
  )
]

#let basic_construction = [
  We wish to realize a Coxeter group, returning it to its geometric origins.
  This is the idea behind the *basic construction* $cal(U)(W, X)$.

  We begin with some additional definitions.
  If $(W, S)$ is a Coxeter system and $X$ is a connected and Hausdorff topological space, define a *mirror structure* on $X$ over $S$ by a collection $(X_s)_(s in S)$, where each $X_s$ is a nonempty, closed subset of $X$.
  Call each $X_s$ the $s$-mirror of $X$.
  The idea is to "glue" copies of $X$ along the mirrors.

  For each point $x in X$, define $S(x) subset.eq S$ by $S(x) := {s in S : x in X_s}$.
  Define a relation $sim$ on $W times X$ by
  $
    (w, x) sim (w', x') "if and only if" x = x' "and" inv(w) w' in W_(S(x)).
  $
  Now the basic construction is the quotient
  $
    cal(U)(W, X) = W times X \/ sim
  $
  equipped with the quotient topology.
  We then define the *Davis complex* $Sigma(W, S)$ as $
    Sigma(W, S)
      &= cal(U) (W, K)
  $ where $K$ is a chamber with the mirror structures $(K_s)_(s in S)$ as defined previously.

  #realization_diagram
]

#let Davis_complex_CAT0 = [
  We say a *geodesic space* $X$ is *$"CAT"(0)$* if the triangles in $X$ appear no "fatter" than triangles in a Euclidean space $EE^n$ of same dimension.
  Similarly, we can define *$"CAT"(-1)$* and *$"CAT"(1)$* for triangles in $X$ compared to triangles in hyperbolic space $HH^n$ and spherical space $SS^n$ respectively.
  In order to realize this condition for the Davis complex, we must construct a metric for it.

  We first choose a collection $underline(d) = (d_s)_(s in S)$ for which $d_s > 0$ for any $s in S$.
  For finite $W_T$, let $C_T$ be a chamber in $RR^n$ generated by the intersection of the half spaces produced by the hyperplanes $H_t$ for $t in T$ as in the *Tits Representation*#h(-0.25em).
  Then we can define the unique point $x_T$ in the interior of $C_T$ such that $d(x_T, H_t) = d_t$ for all $t in T$.
  We then metrize each cell of $Sigma(W, S)$, $w W_T$, as a copy of the polytope generated by the $W_T$-orbit of $x_T$ (a standard choice for $underline(d)$ is $d_s = 1/2$ for all $s$ constructing the path metric for the $1$-skeleton of $Sigma(W, S)$).

  Using this metric, it was shown by Moussong and Gromov that the Davis complex for a Coxeter group $W$, $Sigma(W, S)$, is a complete $"CAT"(0)$ space.
  This result implies the *contractability* of the Davis complex, and shows that the *word problem* (whether two words represent the same element) and *conjugacy problem* (whether two words represent conjugate elements) are solvable for $W$.
]

#let tits_representation = [
  A key result due to Jacques Tits gives a faithful linear representation for $(W, S)$, $
    rho : W -> GL_n (RR),
  $ with $n = |S|$, such that for each $s_i in S$, $rho(s_i) = sigma_i$ is a linear involution whose fixed set is a hyperplane and for all $i != j$, the product $sigma_i sigma_j$ has order $m_(i j)$.
  Consider the real vector space $V$ with basis ${e_1, dots, e_n}$, and define a symmetric bilinear form $B$ on $V$ by
  $
    B(e_i, e_j) = cases(
      -cos(pi / m_(i j)) &"if" m_(i j) "is finite" \
      -1 &"if" m_(i j) = infty.
    )
  $
  Then define the hyperplanes by $H_i = {v in V : B (e_i, v) = 0}$ and the linear maps by $ sigma_i (v) = v - 2B(e_i, v) e_i, $
  which we note is the usual form of reflections in Euclidean geometry.
]

#let buildings = [
  A *building of type* $(W, S)$ is a simplicial complex $Delta$, which is a union of subcomplexes called *apartments*#h(-0.4em), where each apartment is a copy of the *Coxeter complex* (or alternatively the Davis complex) for $(W, S)$.
  With _chambers_ defined to be the maximal simplices in $Delta$, the following hold:
  1. Any two chambers are contained in a common apartment
  2. If $A$ and $A'$ are arbitrary apartments, then there is an isomorphism $A -> A'$ which fixes $A inter A'$ pointwise

  #align(horizon)[#grid(
    columns: (1fr, 1fr),
    buildings_diagram,
    [
      For example, take the infinite dihedral group
      $
        W = gen(s\, t | s^2 = t^2 = 1) iso D_infty,
      $
      whose Coxeter complex (and similarly its Davis complex) is the tessellation of the real line $EE^1$ under the action of $W$.

      The 3-regular tree $T_3$ (shown to the left) is a building of type $(W, S)$ when we take the system of apartments to be the collection of all bi-infinite lines in $T_3$. Each line segment corresponds to a chamber in the building and each path through the tree corresponds to a single Davis complex $Sigma(W, S)$.
    ],
  )]

  Observe that the first condition is satisfied since any two edges in the tree are contained in a common line.
  The second condition follows because we can trivially find a map between any pair of bi-infinite lines.
  Thus, $T_3$ is a building of type $(W, S)$.
]

#let acknowledgements = [
  We want to thank our mentor, Benedict Lee, for his guidance and support in our readings and the Directed Reading Program at UCSB for this opportunity.
  Finally, we thank the contributors to the Typst typsetting language for making this poster a joy to create.
  #v(-1em)
]

#let references = [
  #bibliography("./books.bib", title: [], full: true)
]
